name: react app CI
on:
  pull-request:
    branches: [master]

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup CI environment
        run: make build-ci-env
      - name: Start CI environment
        run: make start-ci-env
      - name: Wait for selenium hub to be ready
        run: make wait-ci-env
      - name: Start tests
        run: make start-ci-test     
      - name: Deploy
        run: echo "you can add deployment steps from now on. Remaining steps will be running after previous steps passed."  